services:
  platinumrx-app:
    build: .
    image: platinumrx:latest
    container_name: platinumrx-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
